#  Linear algebra and calculus in NumPy

## Linear Algebra Tasks

### 1. Matrix Creation and Manipulation

In [12]:
#Create various types of matrices (zero matrix, identity matrix, random matrix).
import numpy as np

# Zero matrix
zero_matrix = np.zeros((3, 3))

# Identity matrix
identity_matrix = np.eye(3)

# Random matrix
random_matrix = np.random.random((3, 3))

print("\nZero Matrix:\n", zero_matrix)
print("\nIdentity Matrix:\n", identity_matrix)
print("\nRandom Matrix:\n", random_matrix)

#Perform basic matrix operations (addition, subtraction, multiplication).
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Addition
addition = A + B

# Subtraction
subtraction = A - B

# Multiplication
multiplication = np.dot(A, B)  # or A @ B

print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)

#Transpose a matrix and find the determinant and inverse of a matrix.
# Transpose
transpose = np.transpose(A)

# Determinant
determinant = np.linalg.det(A)

# Inverse
inverse = np.linalg.inv(A) if np.linalg.det(A) != 0 else "Matrix is singular, can't find inverse."

print("\nTranspose:\n", transpose)
print("\nDeterminant:\n", determinant)
print("\nInverse:\n", inverse)



Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[0.52066264 0.71107468 0.92805881]
 [0.53008161 0.77932905 0.5757789 ]
 [0.89306362 0.84468044 0.03685737]]

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant:
 -9.51619735392994e-16

Inverse:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


### 2. Solving Linear Equations

In [34]:
#Use NumPy to solve a system of linear equations.
# Coefficient matrix
A = np.array([[3, 1], [1, 2]])

# Constants vector
b = np.array([9, 8])

# Solution
x = np.linalg.solve(A, b)

print("Solution x:\n", x)

#Implement matrix factorization methods (LU decomposition, QR decomposition).
#LU Decomposition
from scipy.linalg import lu

P, L, U = lu(A)
print("\n P:\n", P)
print("\n L:\n", L)
print("\n U:\n", U)

#QR Decomposition
Q, R = np.linalg.qr(A)
print("\n Q:\n", Q)
print("\n R:\n", R)


Solution x:
 [2. 3.]

 P:
 [[1. 0.]
 [0. 1.]]

 L:
 [[1.         0.        ]
 [0.33333333 1.        ]]

 U:
 [[3.         1.        ]
 [0.         1.66666667]]

 Q:
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]

 R:
 [[-3.16227766 -1.58113883]
 [ 0.          1.58113883]]


### 3. Eigenvalues and Eigenvectors

In [24]:
#Calculate the eigenvalues and eigenvectors of a given matrix.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\n Eigenvalues:\n", eigenvalues)
print("\n Eigenvectors:\n", eigenvectors)

#Verify the results by reconstructing the original matrix.
reconstruction = np.dot(eigenvectors, np.dot(np.diag(eigenvalues), np.linalg.inv(eigenvectors)))
print("\n Reconstructed Matrix:\n", reconstruction)



 Eigenvalues:
 [3.61803399 1.38196601]

 Eigenvectors:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

 Reconstructed Matrix:
 [[3. 1.]
 [1. 2.]]


### 4. Vector Operations

In [29]:
#Perform basic vector operations (addition, dot product, cross product).

# Define two vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
vector_addition = np.add(v1, v2)

# Dot Product
dot_product = np.dot(v1, v2)

# Cross Product
cross_product = np.cross(v1, v2)

print("Vector Addition:\n", vector_addition)
print("\nDot Product:\n", dot_product)
print("\nCross Product:\n", cross_product)

#Normalize a vector and compute vector norms.

# Normalize vector
v_norm = v1 / np.linalg.norm(v1)

# Compute norms
l2_norm = np.linalg.norm(v1)
l1_norm = np.linalg.norm(v1, 1)
linf_norm = np.linalg.norm(v1, np.inf)

print("\nNormalized Vector:\n", v_norm)
print("\nL2 Norm:\n", l2_norm)
print("\nL1 Norm:\n", l1_norm)
print("\nLinf Norm:\n", linf_norm)


Vector Addition:
 [5 7 9]

Dot Product:
 32

Cross Product:
 [-3  6 -3]

Normalized Vector:
 [0.26726124 0.53452248 0.80178373]

L2 Norm:
 3.7416573867739413

L1 Norm:
 6.0

Linf Norm:
 3.0


### Matrix Decomposition

In [32]:
#Understand and implement Principal Component Analysis (PCA) using SVD.

# Generate random data
data = np.random.random((5, 3))

# Center data
data_centered = data - np.mean(data, axis=0)

# SVD
U, S, Vt = np.linalg.svd(data_centered)

# PCA components
principal_components = Vt.T

print("Principal Components:\n", principal_components)


Principal Components:
 [[ 0.29347273  0.41241846  0.86242957]
 [ 0.42377634 -0.86479338  0.26934368]
 [-0.8569057  -0.28643222  0.42856646]]


## Calculus Tasks

### 1. Numerical Differentiation


In [41]:
def f(x):
    return x**2 + 3*x + 2

# Forward difference
def forward_diff(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h

# Backward difference
def backward_diff(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

# Central difference
def central_diff(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

x_val = 2
print("Forward Difference:", forward_diff(f, x_val))
print("Backward Difference:", backward_diff(f, x_val))
print("Central Difference:", central_diff(f, x_val))

Forward Difference: 7.000010000091094
Backward Difference: 6.999990000089439
Central Difference: 7.0000000000902665


### 2. Numerical Integration

In [43]:
def f(x):
    return x**2 + 3*x + 2

# Trapezoidal rule
def trapezoidal_rule(f, a, b, n=1000):
    x = np.linspace(a, b, n)
    y = f(x)
    return (b - a) / (2 * n) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])

# Simpson's rule
def simpsons_rule(f, a, b, n=1000):
    if n % 2:
        n += 1
    x = np.linspace(a, b, n)
    y = f(x)
    h = (b - a) / n
    return h / 3 * (y[0] + 2 * np.sum(y[2:-1:2]) + 4 * np.sum(y[1::2]) + y[-1])

a, b = 0, 1
print("Trapezoidal Rule:", trapezoidal_rule(f, a, b))
print("Simpson's Rule:", simpsons_rule(f, a, b))

Trapezoidal Rule: 3.8295001668335003
Simpson's Rule: 3.8355008341675005


### 3. Partial Derivatives

In [46]:
def f(x, y):
    return x**2 + y**2 + 3*x + 2*y

# Partial derivative w.r.t. x
def partial_x(f, x, y, h=1e-5):
    return (f(x + h, y) - f(x, y)) / h

# Partial derivative w.r.t. y
def partial_y(f, x, y, h=1e-5):
    return (f(x, y + h) - f(x, y)) / h

x_val, y_val = 2, 3
print("Partial Derivative w.r.t. x:", partial_x(f, x_val, y_val))
print("Partial Derivative w.r.t. y:", partial_y(f, x_val, y_val))


Partial Derivative w.r.t. x: 7.0000100002687295
Partial Derivative w.r.t. y: 8.000009999875601


### 4. Optimization


In [49]:
from scipy.optimize import minimize

# Objective function
def objective(x):
    return x[0]**2 + x[1]**2

# Constraints
cons = ({'type': 'eq', 'fun': lambda x: x[0] + x[1] - 1},)

# Initial guess
x0 = [0.5, 0.5]

# Solve optimization problem
solution = minimize(objective, x0, constraints=cons)

print("Optimal Solution:", solution.x)

Optimal Solution: [0.5 0.5]
