# NumPy arrays

In [2]:
import numpy as np

In [30]:
# 1. Create a 1D NumPy array containing the integers from 0 to 9.
array_1d = np.arange(10)
print("1D array:", array_1d)

1D array: [0 1 2 3 4 5 6 7 8 9]


In [6]:
# 2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20.
array_2d = np.random.randint(1, 21, size=(3, 3))
print("\n2D array (3x3) with random integers between 1 and 20:\n", array_2d)



2D array (3x3) with random integers between 1 and 20:
 [[12 10  5]
 [ 7  9 17]
 [15 17  1]]


In [8]:
# 3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
array_3d = np.ones((2, 3, 4))
print("\n3D array (2, 3, 4) filled with ones:\n", array_3d)



3D array (2, 3, 4) filled with ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [10]:
# 4. Add two 1D arrays element-wise.
array_1d_1 = np.array([1, 2, 3])
array_1d_2 = np.array([4, 5, 6])
added_1d = np.add(array_1d_1, array_1d_2)
print("\nElement-wise addition of two 1D arrays:", added_1d)



Element-wise addition of two 1D arrays: [5 7 9]


In [12]:
# 5. Multiply two 2D arrays element-wise.
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
multiplied_2d = np.multiply(array_2d_1, array_2d_2)
print("\nElement-wise multiplication of two 2D arrays:\n", multiplied_2d)



Element-wise multiplication of two 2D arrays:
 [[ 5 12]
 [21 32]]


In [14]:
# 6. Calculate the dot product of two matrices.
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_1, matrix_2)
print("\nDot product of two matrices:\n", dot_product)



Dot product of two matrices:
 [[19 22]
 [43 50]]


In [16]:
# 7. Calculate the mean, median, and standard deviation of a 1D array.
array_1d_stats = np.array([1, 2, 3, 4, 5])
mean = np.mean(array_1d_stats)
median = np.median(array_1d_stats)
std_deviation = np.std(array_1d_stats)
print("\nMean:", mean, "Median:", median, "Standard Deviation:", std_deviation)



Mean: 3.0 Median: 3.0 Standard Deviation: 1.4142135623730951


In [18]:
# 8. Find the maximum and minimum values in a 2D array.
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("\nMaximum value in 2D array:", max_value, "Minimum value in 2D array:", min_value)



Maximum value in 2D array: 17 Minimum value in 2D array: 1


In [20]:
# 9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
random_normal = np.random.normal(0, 1, 1000)
print("\nArray of 1000 random numbers from a normal distribution:\n", random_normal)



Array of 1000 random numbers from a normal distribution:
 [-2.89321748e-01  8.75095420e-02 -2.71490845e-01 -8.58763363e-01
 -9.14755406e-01  6.78487254e-01  2.43219596e+00  1.66652229e-02
  7.55381203e-01 -5.01633190e-01 -6.74150526e-01  1.62878560e+00
 -6.02525131e-01  1.26914836e+00  5.89471011e-01 -9.56570171e-01
  8.33304555e-01  2.32893143e-01 -8.88580613e-02  1.36720637e+00
 -4.99970757e-01  2.25600471e-01 -7.08442551e-01 -2.46797717e+00
 -1.14923841e+00  6.65819823e-01  1.39548769e-01 -1.21495881e+00
  9.43400406e-01 -1.20285421e+00  8.42260944e-01 -5.68703304e-01
 -1.28949678e+00 -1.12318125e+00 -4.08244882e-01  2.37230559e-01
 -1.47122554e+00 -1.94434022e+00  2.56902320e-02 -1.11058984e+00
 -3.18340944e-01  1.31538261e+00 -1.25745649e+00  1.19322196e-02
 -7.41461303e-01 -2.01932790e-01  5.25613802e-01 -6.94050873e-01
 -6.79191771e-01  1.12975618e+00  2.93559560e-01  1.19013070e+00
  4.44839533e-01  4.46854283e-01  4.48389460e-01  1.13186691e+00
 -7.96311469e-01  1.44329704e-0

In [22]:
# 10. Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.
uniform_random_2d = np.random.randint(10, 51, size=(5, 5))
print("\n2D array (5x5) with random integers from a uniform distribution between 10 and 50:\n", uniform_random_2d)



2D array (5x5) with random integers from a uniform distribution between 10 and 50:
 [[46 44 36 43 16]
 [12 34 49 44 25]
 [15 28 35 10 43]
 [47 19 38 19 39]
 [21 49 19 33 21]]


In [24]:
# 11. Calculate the cumulative sum of a 1D array.
cumulative_sum = np.cumsum(array_1d)
print("\nCumulative sum of 1D array:", cumulative_sum)


Cumulative sum of 1D array: [ 0  1  3  6 10 15 21 28 36 45]


In [26]:
# 12. Compute the correlation coefficient matrix of a 2D array.
correlation_matrix = np.corrcoef(array_2d)
print("\nCorrelation coefficient matrix of 2D array:\n", correlation_matrix)


Correlation coefficient matrix of 2D array:
 [[ 1.         -0.99587059  0.92261291]
 [-0.99587059  1.         -0.95382097]
 [ 0.92261291 -0.95382097  1.        ]]


In [28]:
# 13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
rolls = np.random.randint(1, 7, 1000)
counts = np.bincount(rolls)[1:]  # [1:] to remove the zero count since dice roll results are from 1 to 6
print("\nFrequency of each outcome for 1000 rolls of a six-sided die:", counts)


Frequency of each outcome for 1000 rolls of a six-sided die: [145 163 161 169 175 187]


## 1. Calculate Basic Statistics

In [4]:
import numpy as np

def calculate_statistics(arr):
    mean = np.mean(arr)
    median = np.median(arr)
    std_deviation = np.std(arr)
    return mean, median, std_deviation

array_1d = np.array([10, 20, 30, 40, 50])
mean, median, std_deviation = calculate_statistics(array_1d)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_deviation}")


Mean: 30.0, Median: 30.0, Standard Deviation: 14.142135623730951


## 2. Find Maximum and Minimum in a 2D Array

In [6]:
import numpy as np

def find_min_max(matrix):
    max_value = np.max(matrix)
    min_value = np.min(matrix)
    return max_value, min_value

array_2d = np.random.randint(1, 21, size=(3, 3))
max_value, min_value = find_min_max(array_2d)
print(f"2D Array:\n{array_2d}\nMaximum: {max_value}, Minimum: {min_value}")


2D Array:
[[ 2  6 15]
 [10 10 10]
 [11 16  5]]
Maximum: 16, Minimum: 2


## 3. Generate Normal Distribution and Calculate Statistics

In [8]:
import numpy as np

def generate_normal_distribution(mean, std_dev, size):
    return np.random.normal(mean, std_dev, size)

random_numbers = generate_normal_distribution(0, 1, 1000)
mean, median, std_deviation = calculate_statistics(random_numbers)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_deviation}")


Mean: -0.053203700475169105, Median: -0.0555559217309105, Standard Deviation: 1.0245708358805823


## 4. Simulate Dice Rolls and Count Frequencies

In [10]:
import numpy as np

def simulate_dice_rolls(num_rolls):
    rolls = np.random.randint(1, 7, num_rolls)
    counts = np.bincount(rolls)[1:]  # Exclude zero count
    return counts

num_rolls = 1000
frequencies = simulate_dice_rolls(num_rolls)
print(f"Frequencies of each outcome for {num_rolls} rolls: {frequencies}")


Frequencies of each outcome for 1000 rolls: [169 185 146 176 172 152]


## 5. Element-wise Addition and Multiplication of Arrays

In [12]:
import numpy as np

def add_arrays(arr1, arr2):
    return np.add(arr1, arr2)

def multiply_arrays(arr1, arr2):
    return np.multiply(arr1, arr2)

array_1d_1 = np.array([1, 2, 3])
array_1d_2 = np.array([4, 5, 6])
added_1d = add_arrays(array_1d_1, array_1d_2)
print(f"Element-wise addition of 1D arrays: {added_1d}")

array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
multiplied_2d = multiply_arrays(array_2d_1, array_2d_2)
print(f"Element-wise multiplication of 2D arrays:\n{multiplied_2d}")


Element-wise addition of 1D arrays: [5 7 9]
Element-wise multiplication of 2D arrays:
[[ 5 12]
 [21 32]]
