# NumPy arrays

In [1]:
import numpy as np

# 1. Create a 1D NumPy array containing the integers from 0 to 9.
array_1d = np.arange(10)
print("1D array:", array_1d)

# 2. Create a 2D NumPy array (3x3) containing random integers between 1 and 20.
array_2d = np.random.randint(1, 21, size=(3, 3))
print("\n2D array (3x3) with random integers between 1 and 20:\n", array_2d)

# 3. Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
array_3d = np.ones((2, 3, 4))
print("\n3D array (2, 3, 4) filled with ones:\n", array_3d)

# 4. Add two 1D arrays element-wise.
array_1d_1 = np.array([1, 2, 3])
array_1d_2 = np.array([4, 5, 6])
added_1d = np.add(array_1d_1, array_1d_2)
print("\nElement-wise addition of two 1D arrays:", added_1d)

# 5. Multiply two 2D arrays element-wise.
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
multiplied_2d = np.multiply(array_2d_1, array_2d_2)
print("\nElement-wise multiplication of two 2D arrays:\n", multiplied_2d)

# 6. Calculate the dot product of two matrices.
matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_1, matrix_2)
print("\nDot product of two matrices:\n", dot_product)

# 7. Calculate the mean, median, and standard deviation of a 1D array.
array_1d_stats = np.array([1, 2, 3, 4, 5])
mean = np.mean(array_1d_stats)
median = np.median(array_1d_stats)
std_deviation = np.std(array_1d_stats)
print("\nMean:", mean, "Median:", median, "Standard Deviation:", std_deviation)

# 8. Find the maximum and minimum values in a 2D array.
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("\nMaximum value in 2D array:", max_value, "Minimum value in 2D array:", min_value)

# 9. Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.
random_normal = np.random.normal(0, 1, 1000)
print("\nArray of 1000 random numbers from a normal distribution:\n", random_normal)

# 10. Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50.
uniform_random_2d = np.random.randint(10, 51, size=(5, 5))
print("\n2D array (5x5) with random integers from a uniform distribution between 10 and 50:\n", uniform_random_2d)

# 11. Calculate the cumulative sum of a 1D array.
cumulative_sum = np.cumsum(array_1d)
print("\nCumulative sum of 1D array:", cumulative_sum)

# 12. Compute the correlation coefficient matrix of a 2D array.
correlation_matrix = np.corrcoef(array_2d)
print("\nCorrelation coefficient matrix of 2D array:\n", correlation_matrix)

# 13. Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
rolls = np.random.randint(1, 7, 1000)
counts = np.bincount(rolls)[1:]  # [1:] to remove the zero count since dice roll results are from 1 to 6
print("\nFrequency of each outcome for 1000 rolls of a six-sided die:", counts)


1D array: [0 1 2 3 4 5 6 7 8 9]

2D array (3x3) with random integers between 1 and 20:
 [[12 13 11]
 [18 15  6]
 [15 10 16]]

3D array (2, 3, 4) filled with ones:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

Element-wise addition of two 1D arrays: [5 7 9]

Element-wise multiplication of two 2D arrays:
 [[ 5 12]
 [21 32]]

Dot product of two matrices:
 [[19 22]
 [43 50]]

Mean: 3.0 Median: 3.0 Standard Deviation: 1.4142135623730951

Maximum value in 2D array: 18 Minimum value in 2D array: 6

Array of 1000 random numbers from a normal distribution:
 [-8.95527169e-01  2.62839625e-01  1.00156249e+00  1.97660093e-01
 -4.71954551e-01  2.34573103e+00 -1.41281352e+00 -9.46857548e-01
  2.38242534e+00 -2.68592183e-01  1.07711462e+00 -3.54755996e-01
 -1.48996913e+00 -2.35409897e-01 -1.44565994e-01  1.30922619e+00
 -1.73481656e-01  2.93225999e-01 -7.67102249e-01  6.17262340e-01
 -7.59685222e-01  7.88090715e-01  3.20550451e+00 -8.94532389e-01

# 1. Calculate Basic Statistics

In [6]:
import numpy as np

def calculate_statistics(arr):
    mean = np.mean(arr)
    median = np.median(arr)
    std_deviation = np.std(arr)
    return mean, median, std_deviation

array_1d = np.array([10, 20, 30, 40, 50])
mean, median, std_deviation = calculate_statistics(array_1d)
print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_deviation}")


Mean: 30.0, Median: 30.0, Standard Deviation: 14.142135623730951


## 2. Find Maximum and Minimum in a 2D Array

In [9]:
import numpy as np

def find_min_max(matrix):
    max_value = np.max(matrix)
    min_value = np.min(matrix)
    return max_value, min_value

array_2d = np.random.randint(1, 21, size=(3, 3))
max_value, min_value = find_min_max(array_2d)
print(f"2D Array:\n{array_2d}\nMaximum: {max_value}, Minimum: {min_value}")


2D Array:
[[ 3  4  3]
 [17  6 11]
 [11 10  1]]
Maximum: 17, Minimum: 1


## 3. Generate Normal Distribution and Calculate Statistics