## Serial No 23: Areeba Qamar

### Indexing and Slicing


In [13]:
import numpy as np

# 1. Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

array_2d_6x6 = np.random.randint(1, 20, size=(6, 6))
sub_array_2x2 = array_2d_6x6[1:3, 1:3]
print("Original 6x6 array:\n", array_2d_6x6)
print("\nExtracted 2x2 sub-array:\n", sub_array_2x2)

# 2. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.

array_3d = np.random.randint(1, 10, size=(3, 2, 1))
extracted_elements = array_3d[:2, :, 0]
print("\nOriginal 3D array:\n", array_3d)
print("\nExtracted elements:\n", extracted_elements)

# 3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
fancy_indexed_elements = array_1d[[1, 3, 4, 6]]
print("\nOriginal 1D array:\n", array_1d)
print("\nElements at positions [1, 3, 4, 6]:", fancy_indexed_elements)

# 4. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].

array_2d = np.random.randint(1, 20, size=(4, 5))
fancy_indexed_2d = array_2d[[0, 2, 2], :][:, [1, 3]]
print("\nOriginal 2D array:\n", array_2d)
print("\nSelected rows [0, 2, 2] and columns [1, 3]:\n", fancy_indexed_2d)

# 5. From a 1D array of random integers, extract all elements that are greater than 8.

random_1d = np.random.randint(1, 20, size=10)
greater_than_8 = random_1d[random_1d > 8]
print("\nOriginal random 1D array:\n", random_1d)
print("\nElements greater than 8:", greater_than_8)

# 6. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

array_2d_6x6_replace = np.random.randint(1, 20, size=(6, 6))
array_2d_6x6_replace[array_2d_6x6_replace > 13] = 0
print("\nOriginal 6x6 array with elements greater than 13 replaced by 0:\n", array_2d_6x6_replace)


Original 6x6 array:
 [[17  6 14 19 17 17]
 [ 8  2  8 14  6  7]
 [19 15 12  1  7 11]
 [13 18  2 15 14 19]
 [16  3  2 11 10 13]
 [17  4  5 19 11 16]]

Extracted 2x2 sub-array:
 [[ 2  8]
 [15 12]]

Original 3D array:
 [[[7]
  [8]]

 [[8]
  [3]]

 [[6]
  [5]]]

Extracted elements:
 [[7 8]
 [8 3]]

Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]

Elements at positions [1, 3, 4, 6]: [1 3 4 6]

Original 2D array:
 [[ 8  3  4  4 14]
 [ 1 18  8 16  2]
 [13 15 14 15 12]
 [ 2 12 15 15  3]]

Selected rows [0, 2, 2] and columns [1, 3]:
 [[ 3  4]
 [15 15]
 [15 15]]

Original random 1D array:
 [ 8  1 16  3 18  7  3 19  8 11]

Elements greater than 8: [16 18 19 11]

Original 6x6 array with elements greater than 13 replaced by 0:
 [[ 5  9 12 12  7  3]
 [ 1  3  0  3  0  9]
 [ 0  0  0  0  0  8]
 [ 0  0  0  0  1 13]
 [ 0 12 10  9  0 12]
 [ 6  7 11 10  9  7]]


### Broadcasting

In [15]:
# 7. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

array_2d_4x3 = np.random.randint(1, 10, size=(4, 3))
array_1d_3 = np.array([1, 2, 3])
broadcast_added = array_2d_4x3 + array_1d_3
print("\nOriginal 4x3 array:\n", array_2d_4x3)
print("\n1D array added to each row:\n", broadcast_added)

# 8. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

array_2d_3x3 = np.random.randint(1, 10, size=(3, 3))
array_1d_3_mult = np.array([1, 2, 3])
broadcast_multiplied = array_2d_3x3 * array_1d_3_mult
print("\nOriginal 3x3 array:\n", array_2d_3x3)
print("\n1D array multiplied to each row:\n", broadcast_multiplied)

# 9. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

array_2d_3x1 = np.random.randint(1, 10, size=(3, 1))
array_2d_1x4 = np.random.randint(1, 10, size=(1, 4))
broadcast_added_2d = array_2d_3x1 + array_2d_1x4
print("\n3x1 array:\n", array_2d_3x1)
print("\n1x4 array:\n", array_2d_1x4)
print("\nElement-wise addition of 3x1 and 1x4 arrays:\n", broadcast_added_2d)

# 10. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

array_3d_2x3x4 = np.random.randint(1, 10, size=(2, 3, 4))
array_2d_3x4 = np.random.randint(1, 10, size=(3, 4))
broadcast_added_3d = array_3d_2x3x4 + array_2d_3x4
print("\nOriginal 3D array:\n", array_3d_2x3x4)
print("\n2D array:\n", array_2d_3x4)
print("\n2D array added to each slice of 3D array:\n", broadcast_added_3d)


Original 4x3 array:
 [[1 7 4]
 [6 9 1]
 [9 8 2]
 [2 1 3]]

1D array added to each row:
 [[ 2  9  7]
 [ 7 11  4]
 [10 10  5]
 [ 3  3  6]]

Original 3x3 array:
 [[1 5 2]
 [3 5 5]
 [1 1 6]]

1D array multiplied to each row:
 [[ 1 10  6]
 [ 3 10 15]
 [ 1  2 18]]

3x1 array:
 [[5]
 [5]
 [8]]

1x4 array:
 [[5 4 5 5]]

Element-wise addition of 3x1 and 1x4 arrays:
 [[10  9 10 10]
 [10  9 10 10]
 [13 12 13 13]]

Original 3D array:
 [[[4 8 1 7]
  [1 5 7 3]
  [5 2 6 4]]

 [[2 4 6 6]
  [1 7 5 6]
  [3 5 8 2]]]

2D array:
 [[1 1 1 9]
 [1 4 2 1]
 [6 4 7 7]]

2D array added to each slice of 3D array:
 [[[ 5  9  2 16]
  [ 2  9  9  4]
  [11  6 13 11]]

 [[ 3  5  7 15]
  [ 2 11  7  7]
  [ 9  9 15  9]]]


### Some more

In [33]:
# 11. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

array_2d_more = np.random.randint(1, 10, size=(6, 6))
sliced_array = array_2d_more[::2, ::2]
array_1d_add = np.array([1, 2, 3])
broadcast_sliced_added = sliced_array + array_1d_add
print("\nOriginal 6x6 array:\n", array_2d_more)
print("\nSliced every second row and column:\n", sliced_array)
print("\n1D array added to each row of sliced array:\n", broadcast_sliced_added)

# 12. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

array_3d_more = np.random.randint(1, 10, size=(3, 2, 1))
sub_array_3d = array_3d_more[:, :, 0]
array_2d_sub = np.array([[1, 2], [3, 4], [5, 6]])
broadcast_subtracted = sub_array_3d - array_2d_sub
print("\nOriginal 3D array:\n", array_3d_more)
print("\nExtracted sub-array:\n", sub_array_3d)
print("\nSubtracted 2D array from each slice:\n", broadcast_subtracted)

# 13. Given a 2D array, extract the diagonal elements and create a 1D array.

array_2d_diag = np.random.randint(1, 10, size=(5, 5))
diagonal_elements = np.diag(array_2d_diag)
print("\nOriginal 2D array:\n", array_2d_diag)
print("\nDiagonal elements:", diagonal_elements)

# 14. Use slicing to reverse the order of elements in each row of a 2D array.

array_2d_reverse = np.random.randint(1, 10, size=(4, 5))
reversed_rows = array_2d_reverse[:, ::-1]
print("\nOriginal 2D array:\n", array_2d_reverse)
print("\nRows reversed:\n", reversed_rows)

# 15. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

array_3d = np.random.randint(1, 10, size=(7, 6, 5))
sub_array = array_3d[:2, :3, :4]
array_1d = np.array([1, 2, 3, 4])
broadcasted_addition = sub_array + array_1d
print("\nOriginal 3D array:\n", array_3d)
print("\nExtracted sub-array:\n", sub_array)
print("\n1D array to add:", array_1d)
print("\nResult of broadcasting addition:\n", broadcasted_addition,)

# 16. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

array_2d = np.random.randint(1, 10, size=(5, 5))
array_2d[:, -1] = array_2d[:, 0] + array_2d[:, 1]
print("\nModified 2D array with last column set to sum of first two columns:\n", array_2d)




Original 6x6 array:
 [[5 7 9 9 7 3]
 [3 6 9 8 6 8]
 [2 4 1 2 2 1]
 [1 3 8 2 5 8]
 [6 6 3 1 9 3]
 [8 7 7 3 3 9]]

Sliced every second row and column:
 [[5 9 7]
 [2 1 2]
 [6 3 9]]

1D array added to each row of sliced array:
 [[ 6 11 10]
 [ 3  3  5]
 [ 7  5 12]]

Original 3D array:
 [[[3]
  [1]]

 [[6]
  [5]]

 [[6]
  [3]]]

Extracted sub-array:
 [[3 1]
 [6 5]
 [6 3]]

Subtracted 2D array from each slice:
 [[ 2 -1]
 [ 3  1]
 [ 1 -3]]

Original 2D array:
 [[5 8 7 3 6]
 [8 5 1 6 1]
 [3 3 5 4 6]
 [5 2 8 9 1]
 [1 3 7 1 2]]

Diagonal elements: [5 5 5 9 2]

Original 2D array:
 [[1 6 2 1 7]
 [9 8 8 7 2]
 [3 8 3 4 1]
 [3 8 8 4 4]]

Rows reversed:
 [[7 1 2 6 1]
 [2 7 8 8 9]
 [1 4 3 8 3]
 [4 4 8 8 3]]

Original 3D array:
 [[[1 3 3 1 3]
  [4 9 2 9 3]
  [6 7 7 3 3]
  [3 5 2 1 8]
  [7 7 2 6 8]
  [5 2 9 9 3]]

 [[5 7 9 1 5]
  [1 1 2 5 6]
  [3 8 2 8 9]
  [2 1 2 2 4]
  [2 4 4 1 9]
  [4 6 6 4 9]]

 [[7 1 2 6 8]
  [5 1 4 3 9]
  [2 1 1 5 2]
  [6 6 3 9 3]
  [7 9 5 9 5]
  [6 5 5 9 1]]

 [[4 3 3 1 5]
  [1 4 